name = "cleanup-worker"
main = "workers/cleanup.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# 每 1 小时运行一次
[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
migrations_dir = "drizzle"
database_name = ""
database_id = ""
